#!/usr/bin/with-contenv bash

if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg software-properties-common
fi

if [ ! -f "/etc/apt/sources.list.d/hashicorp.list" ]; then
    echo "**** Adding terraform packages to install list ****"
    apt-get install -y gnupg software-properties-common wget curl
    wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    source /etc/lsb-release
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    echo "terraform" >> /mod-repo-packages-to-install.list
else
    echo "**** Terraform packages already installed, skipping ****"
fi
