---
version: ""
services:
  mywebtop:
    image: redbeard28/mywebtop:0.1
    container_name: webtop
    networks:
      - mynet
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SUBFOLDER=/ #optional
      - KEYBOARD=fr-fr-azerty #optional
      - TITLE=Kumalabs #optional
      - AUTO_LOGIN=false
      - FILE__PASSWORD="./wetopsecret"
    volumes:
      - ./mywebtop/home:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
# JUSTE ON LINUX
#    devices:
#      - /dev/dri:/dev/dri #optional
    shm_size: "8gb" #optional
    restart: unless-stopped

networks:
  mynet:
    driver: bridge