#!/usr/bin/with-contenv bash
# shellcheck shell=bash

source /etc/lsb-release

[[ ! -f "/etc/apt/sources.list.d/hashicorp.list" ]] &&
  echo "------------------ Add Hashicorp sources"
  apt-get update
  apt-get install -y gnupg software-properties-common wget curl
  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list